GET http://localhost:3000/api/product/

# POST http://localhost:3000/api/product
# Content-Type: application/json

# {
#   "productId": "456",
#   "productName": "New Product",
#   "productOwnerName": "New Product Owner",
#   "Developers": [
#     "Developer 1",
#     "Developer 2"
#   ],
#   "scrumMasterName": "Scrum Master",
#   "startDate": "2022/04/01",
#   "methodology": "Agile"
# }

# PUT http://localhost:3000/api/product/456
# Content-Type: application/json

# {
#   "productName": "New Product Name",
#   "productOwnerName": "New Product Owner Name"
# }

DELETE http://localhost:3000/api/product/456
